### ISSUE TITLE
IFort21 compiler error c0000005

### ISSUE THREAD

**Issue by Smurf-IV** [oneapi-src/oneapi-ci#54]
1>fortcom: Fatal: There has been an internal compiler error (C0000005).
1>compilation aborted for #######\SrFortBase\ROUTINES\error_handler.f90 (code 1)

Visual Studio 2022 - 17.0.6

This code compiles using VS 2017 and iFort 18.4

[SrFortBase.zip](https://github.com/oneapi-src/oneapi-ci/files/8159735/SrFortBase.zip)

**Comment by Smurf-IV** [comment]
Note: Please move to the correct area, as the intel website for reporting new incidents with a new users is down!
